name: Build

on:
  push:
    branches: [ "main", "fix" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check
      run: cargo clippy
    - name: Build
      run: cargo build -vv
    - name: Run tests
      run: cargo test -vv
    - name: Build examples
      run: cargo b --example demo -vv
